name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sub_player:
    path: ../
  cupertino_icons: ^1.0.5
  riverpod_generator: ^1.1.1
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
  icons_launcher: ^2.0.6
  logger: ^1.1.0
  google_fonts: ^4.0.2
  flutter_emoji: ^2.4.0
  dio: ^5.1.0
  get_it: ^7.2.0
  go_router: ^6.0.3
  adaptive_dialog: ^1.8.2
  video_player: ^2.6.0
  readmore: ^2.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.4
  wakelock: ^0.6.2
  modal_bottom_sheet: ^2.1.2
  snapping_sheet: ^3.1.0
  video_player_tizen: ^2.4.5
  wakelock_tizen: ^1.0.1
  path_provider_tizen: ^2.1.0
  flutter_tizen: ^0.2.1
  shimmer: ^2.0.0
  video_player_web_hls: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  isar_generator: ^3.0.5
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
