name: example
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sub_player:
    path: ../
  cupertino_icons: ^1.0.5
  riverpod_generator: ^1.1.1
  flutter_riverpod: ^2.1.3
  hooks_riverpod: ^2.1.3
  flutter_hooks: ^0.18.5+1
  icons_launcher: ^2.0.6
  logger: ^1.1.0
  google_fonts: ^4.0.2
  flutter_emoji: ^2.4.0
  dio: ^4.0.6
  get_it: ^7.2.0
  go_router: ^6.0.3

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: any
  flutter_test:
    sdk: flutter
  freezed: any
  isar_generator: ^3.0.5
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true